{"uuid":"589c9bac-883a-43fb-801c-3c6f68859fb7","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > (0 , _stringTools.getRandomPostfix) is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > (0 , _stringTools.getRandomPostfix) is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Object../cypress/support/fragments/invoices/newBatchGroup.js (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:188:45)\n    at __webpack_require__ (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:20:30)\n    at Object../cypress/integration/invoices/settings/invoices.settings.createBatchGroup.spec.js (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:105:45)\n    at __webpack_require__ (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:20:30)\n    at Object.0 (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:49090:18)\n    at __webpack_require__ (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:20:30)\n    at eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:84:18)\n    at eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress\\integration\\invoices\\settings\\invoices.settings.createBatchGroup.spec.js:87:10)\n    at eval (<anonymous>)\nFrom previous event:\n    at runScriptsFromUrls (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:179443:136)\n    at Object.runScripts (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:179458:12)\n    at $Cypress.onSpecWindow (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:168185:76)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[],"links":[],"start":1644507048198,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1644507048258}